flowchart 


A["Rectangle"]
B("Rounded rectangle")
C{Decision}
D[(Database)]
E((Circle))
F(["Stadium / Pill"])
G[[Subroutine]]
H[/Input/]
I[\Output\]
J[/Trapezoid\]
K[\Inverted trapezoid/]
L{{Hexagon}}
M(((Cloud)))
N>Flag]

A --> B --> C --> D --> E --> F --> G --> H --> I --> J --> K --> L --> M --> N
